//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebSerrviceIntAptus.br.com.aptuscloud.mooz {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ID_ADSoap", Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class ID_AD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AtualizarIntegradoSituacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarIntegracaoSucessoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarIntegracaoProblemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstornarIntegracaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterAdiantamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterAdiantamentosPendentesResumoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterAdiantamentosPendentesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ID_AD() {
            this.Url = global::WebSerrviceIntAptus.Properties.Settings.Default.WebSerrviceIntAptus_br_com_aptuscloud_mooz_ID_AD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AtualizarIntegradoSituacaoCompletedEventHandler AtualizarIntegradoSituacaoCompleted;
        
        /// <remarks/>
        public event AtualizarIntegracaoSucessoCompletedEventHandler AtualizarIntegracaoSucessoCompleted;
        
        /// <remarks/>
        public event AtualizarIntegracaoProblemaCompletedEventHandler AtualizarIntegracaoProblemaCompleted;
        
        /// <remarks/>
        public event EstornarIntegracaoCompletedEventHandler EstornarIntegracaoCompleted;
        
        /// <remarks/>
        public event ObterAdiantamentoCompletedEventHandler ObterAdiantamentoCompleted;
        
        /// <remarks/>
        public event ObterAdiantamentosPendentesResumoCompletedEventHandler ObterAdiantamentosPendentesResumoCompleted;
        
        /// <remarks/>
        public event ObterAdiantamentosPendentesCompletedEventHandler ObterAdiantamentosPendentesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aptuscloud.com.br/rdapi/AtualizarIntegradoSituacao", RequestNamespace="http://aptuscloud.com.br/rdapi/", ResponseNamespace="http://aptuscloud.com.br/rdapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoEletronica AtualizarIntegradoSituacao(string accessKey, string empresa, string codigoIntegracao, string codigoStatus, string mensagemStatus) {
            object[] results = this.Invoke("AtualizarIntegradoSituacao", new object[] {
                        accessKey,
                        empresa,
                        codigoIntegracao,
                        codigoStatus,
                        mensagemStatus});
            return ((IntegracaoEletronica)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizarIntegradoSituacaoAsync(string accessKey, string empresa, string codigoIntegracao, string codigoStatus, string mensagemStatus) {
            this.AtualizarIntegradoSituacaoAsync(accessKey, empresa, codigoIntegracao, codigoStatus, mensagemStatus, null);
        }
        
        /// <remarks/>
        public void AtualizarIntegradoSituacaoAsync(string accessKey, string empresa, string codigoIntegracao, string codigoStatus, string mensagemStatus, object userState) {
            if ((this.AtualizarIntegradoSituacaoOperationCompleted == null)) {
                this.AtualizarIntegradoSituacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarIntegradoSituacaoOperationCompleted);
            }
            this.InvokeAsync("AtualizarIntegradoSituacao", new object[] {
                        accessKey,
                        empresa,
                        codigoIntegracao,
                        codigoStatus,
                        mensagemStatus}, this.AtualizarIntegradoSituacaoOperationCompleted, userState);
        }
        
        private void OnAtualizarIntegradoSituacaoOperationCompleted(object arg) {
            if ((this.AtualizarIntegradoSituacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarIntegradoSituacaoCompleted(this, new AtualizarIntegradoSituacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aptuscloud.com.br/rdapi/AtualizarIntegracaoSucesso", RequestNamespace="http://aptuscloud.com.br/rdapi/", ResponseNamespace="http://aptuscloud.com.br/rdapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoEletronica AtualizarIntegracaoSucesso(string accessKey, string empresa, string codigo, string codigoIntegracao) {
            object[] results = this.Invoke("AtualizarIntegracaoSucesso", new object[] {
                        accessKey,
                        empresa,
                        codigo,
                        codigoIntegracao});
            return ((IntegracaoEletronica)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizarIntegracaoSucessoAsync(string accessKey, string empresa, string codigo, string codigoIntegracao) {
            this.AtualizarIntegracaoSucessoAsync(accessKey, empresa, codigo, codigoIntegracao, null);
        }
        
        /// <remarks/>
        public void AtualizarIntegracaoSucessoAsync(string accessKey, string empresa, string codigo, string codigoIntegracao, object userState) {
            if ((this.AtualizarIntegracaoSucessoOperationCompleted == null)) {
                this.AtualizarIntegracaoSucessoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarIntegracaoSucessoOperationCompleted);
            }
            this.InvokeAsync("AtualizarIntegracaoSucesso", new object[] {
                        accessKey,
                        empresa,
                        codigo,
                        codigoIntegracao}, this.AtualizarIntegracaoSucessoOperationCompleted, userState);
        }
        
        private void OnAtualizarIntegracaoSucessoOperationCompleted(object arg) {
            if ((this.AtualizarIntegracaoSucessoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarIntegracaoSucessoCompleted(this, new AtualizarIntegracaoSucessoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aptuscloud.com.br/rdapi/AtualizarIntegracaoProblema", RequestNamespace="http://aptuscloud.com.br/rdapi/", ResponseNamespace="http://aptuscloud.com.br/rdapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoEletronica AtualizarIntegracaoProblema(string accessKey, string empresa, string codigo, string problemaCodigo, string problemaMensagem) {
            object[] results = this.Invoke("AtualizarIntegracaoProblema", new object[] {
                        accessKey,
                        empresa,
                        codigo,
                        problemaCodigo,
                        problemaMensagem});
            return ((IntegracaoEletronica)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizarIntegracaoProblemaAsync(string accessKey, string empresa, string codigo, string problemaCodigo, string problemaMensagem) {
            this.AtualizarIntegracaoProblemaAsync(accessKey, empresa, codigo, problemaCodigo, problemaMensagem, null);
        }
        
        /// <remarks/>
        public void AtualizarIntegracaoProblemaAsync(string accessKey, string empresa, string codigo, string problemaCodigo, string problemaMensagem, object userState) {
            if ((this.AtualizarIntegracaoProblemaOperationCompleted == null)) {
                this.AtualizarIntegracaoProblemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarIntegracaoProblemaOperationCompleted);
            }
            this.InvokeAsync("AtualizarIntegracaoProblema", new object[] {
                        accessKey,
                        empresa,
                        codigo,
                        problemaCodigo,
                        problemaMensagem}, this.AtualizarIntegracaoProblemaOperationCompleted, userState);
        }
        
        private void OnAtualizarIntegracaoProblemaOperationCompleted(object arg) {
            if ((this.AtualizarIntegracaoProblemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarIntegracaoProblemaCompleted(this, new AtualizarIntegracaoProblemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aptuscloud.com.br/rdapi/EstornarIntegracao", RequestNamespace="http://aptuscloud.com.br/rdapi/", ResponseNamespace="http://aptuscloud.com.br/rdapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoEletronica EstornarIntegracao(string accessKey, string empresa, string codigo) {
            object[] results = this.Invoke("EstornarIntegracao", new object[] {
                        accessKey,
                        empresa,
                        codigo});
            return ((IntegracaoEletronica)(results[0]));
        }
        
        /// <remarks/>
        public void EstornarIntegracaoAsync(string accessKey, string empresa, string codigo) {
            this.EstornarIntegracaoAsync(accessKey, empresa, codigo, null);
        }
        
        /// <remarks/>
        public void EstornarIntegracaoAsync(string accessKey, string empresa, string codigo, object userState) {
            if ((this.EstornarIntegracaoOperationCompleted == null)) {
                this.EstornarIntegracaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstornarIntegracaoOperationCompleted);
            }
            this.InvokeAsync("EstornarIntegracao", new object[] {
                        accessKey,
                        empresa,
                        codigo}, this.EstornarIntegracaoOperationCompleted, userState);
        }
        
        private void OnEstornarIntegracaoOperationCompleted(object arg) {
            if ((this.EstornarIntegracaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstornarIntegracaoCompleted(this, new EstornarIntegracaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aptuscloud.com.br/rdapi/ObterAdiantamento", RequestNamespace="http://aptuscloud.com.br/rdapi/", ResponseNamespace="http://aptuscloud.com.br/rdapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoEletronica ObterAdiantamento(string accessKey, string empresa, string codigo) {
            object[] results = this.Invoke("ObterAdiantamento", new object[] {
                        accessKey,
                        empresa,
                        codigo});
            return ((IntegracaoEletronica)(results[0]));
        }
        
        /// <remarks/>
        public void ObterAdiantamentoAsync(string accessKey, string empresa, string codigo) {
            this.ObterAdiantamentoAsync(accessKey, empresa, codigo, null);
        }
        
        /// <remarks/>
        public void ObterAdiantamentoAsync(string accessKey, string empresa, string codigo, object userState) {
            if ((this.ObterAdiantamentoOperationCompleted == null)) {
                this.ObterAdiantamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterAdiantamentoOperationCompleted);
            }
            this.InvokeAsync("ObterAdiantamento", new object[] {
                        accessKey,
                        empresa,
                        codigo}, this.ObterAdiantamentoOperationCompleted, userState);
        }
        
        private void OnObterAdiantamentoOperationCompleted(object arg) {
            if ((this.ObterAdiantamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterAdiantamentoCompleted(this, new ObterAdiantamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aptuscloud.com.br/rdapi/ObterAdiantamentosPendentesResumo", RequestNamespace="http://aptuscloud.com.br/rdapi/", ResponseNamespace="http://aptuscloud.com.br/rdapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoEletronica ObterAdiantamentosPendentesResumo(string accessKey, string empresa) {
            object[] results = this.Invoke("ObterAdiantamentosPendentesResumo", new object[] {
                        accessKey,
                        empresa});
            return ((IntegracaoEletronica)(results[0]));
        }
        
        /// <remarks/>
        public void ObterAdiantamentosPendentesResumoAsync(string accessKey, string empresa) {
            this.ObterAdiantamentosPendentesResumoAsync(accessKey, empresa, null);
        }
        
        /// <remarks/>
        public void ObterAdiantamentosPendentesResumoAsync(string accessKey, string empresa, object userState) {
            if ((this.ObterAdiantamentosPendentesResumoOperationCompleted == null)) {
                this.ObterAdiantamentosPendentesResumoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterAdiantamentosPendentesResumoOperationCompleted);
            }
            this.InvokeAsync("ObterAdiantamentosPendentesResumo", new object[] {
                        accessKey,
                        empresa}, this.ObterAdiantamentosPendentesResumoOperationCompleted, userState);
        }
        
        private void OnObterAdiantamentosPendentesResumoOperationCompleted(object arg) {
            if ((this.ObterAdiantamentosPendentesResumoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterAdiantamentosPendentesResumoCompleted(this, new ObterAdiantamentosPendentesResumoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aptuscloud.com.br/rdapi/ObterAdiantamentosPendentes", RequestNamespace="http://aptuscloud.com.br/rdapi/", ResponseNamespace="http://aptuscloud.com.br/rdapi/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoEletronica ObterAdiantamentosPendentes(string accessKey, string empresa) {
            object[] results = this.Invoke("ObterAdiantamentosPendentes", new object[] {
                        accessKey,
                        empresa});
            return ((IntegracaoEletronica)(results[0]));
        }
        
        /// <remarks/>
        public void ObterAdiantamentosPendentesAsync(string accessKey, string empresa) {
            this.ObterAdiantamentosPendentesAsync(accessKey, empresa, null);
        }
        
        /// <remarks/>
        public void ObterAdiantamentosPendentesAsync(string accessKey, string empresa, object userState) {
            if ((this.ObterAdiantamentosPendentesOperationCompleted == null)) {
                this.ObterAdiantamentosPendentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterAdiantamentosPendentesOperationCompleted);
            }
            this.InvokeAsync("ObterAdiantamentosPendentes", new object[] {
                        accessKey,
                        empresa}, this.ObterAdiantamentosPendentesOperationCompleted, userState);
        }
        
        private void OnObterAdiantamentosPendentesOperationCompleted(object arg) {
            if ((this.ObterAdiantamentosPendentesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterAdiantamentosPendentesCompleted(this, new ObterAdiantamentosPendentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class IntegracaoEletronica {
        
        private RelatorioDespesaResumido[] relatoriosResumidosField;
        
        private RelatorioDespesa[] relatoriosField;
        
        private AdiantamentoResumido[] adiantamentosResumidosField;
        
        private Adiantamento[] adiantamentosField;
        
        private string statusRetornoField;
        
        private string mensagemRetornoField;
        
        private int tempoProcessamentoField;
        
        /// <remarks/>
        public RelatorioDespesaResumido[] RelatoriosResumidos {
            get {
                return this.relatoriosResumidosField;
            }
            set {
                this.relatoriosResumidosField = value;
            }
        }
        
        /// <remarks/>
        public RelatorioDespesa[] Relatorios {
            get {
                return this.relatoriosField;
            }
            set {
                this.relatoriosField = value;
            }
        }
        
        /// <remarks/>
        public AdiantamentoResumido[] AdiantamentosResumidos {
            get {
                return this.adiantamentosResumidosField;
            }
            set {
                this.adiantamentosResumidosField = value;
            }
        }
        
        /// <remarks/>
        public Adiantamento[] Adiantamentos {
            get {
                return this.adiantamentosField;
            }
            set {
                this.adiantamentosField = value;
            }
        }
        
        /// <remarks/>
        public string StatusRetorno {
            get {
                return this.statusRetornoField;
            }
            set {
                this.statusRetornoField = value;
            }
        }
        
        /// <remarks/>
        public string MensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
            }
        }
        
        /// <remarks/>
        public int TempoProcessamento {
            get {
                return this.tempoProcessamentoField;
            }
            set {
                this.tempoProcessamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatorioDespesa))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class RelatorioDespesaResumido {
        
        private string codigoField;
        
        private string dataCriacaoField;
        
        private string dataEnvioField;
        
        private string dataPrevisaoPagamentoField;
        
        private string dataUltimaAprovacaoField;
        
        private string ultimoAprovadorCodigoField;
        
        private string ultimoAprovadorDescricaoField;
        
        private string statusCodigoField;
        
        private string statusDescricaoField;
        
        private string solicitanteIdField;
        
        private string solicitanteCodigoField;
        
        private string usuarioCodigoField;
        
        private string solicitanteNomeField;
        
        private string empresaCodigoField;
        
        private string empresaCNPJField;
        
        private string empresaCodigoERPField;
        
        private string moedaCodigoField;
        
        private string moedaDescricaoField;
        
        private decimal valorTotalField;
        
        private decimal valorReembolsoField;
        
        private decimal valorAdiantamentoField;
        
        private decimal cotacaoIndiceField;
        
        private decimal valorTotalIndiceField;
        
        private decimal valorReembolsoIndiceField;
        
        private decimal valorAdiantamentoIndiceField;
        
        private string textoCabecalhoField;
        
        private string chaveField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string DataCriacao {
            get {
                return this.dataCriacaoField;
            }
            set {
                this.dataCriacaoField = value;
            }
        }
        
        /// <remarks/>
        public string DataEnvio {
            get {
                return this.dataEnvioField;
            }
            set {
                this.dataEnvioField = value;
            }
        }
        
        /// <remarks/>
        public string DataPrevisaoPagamento {
            get {
                return this.dataPrevisaoPagamentoField;
            }
            set {
                this.dataPrevisaoPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string DataUltimaAprovacao {
            get {
                return this.dataUltimaAprovacaoField;
            }
            set {
                this.dataUltimaAprovacaoField = value;
            }
        }
        
        /// <remarks/>
        public string UltimoAprovadorCodigo {
            get {
                return this.ultimoAprovadorCodigoField;
            }
            set {
                this.ultimoAprovadorCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string UltimoAprovadorDescricao {
            get {
                return this.ultimoAprovadorDescricaoField;
            }
            set {
                this.ultimoAprovadorDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCodigo {
            get {
                return this.statusCodigoField;
            }
            set {
                this.statusCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescricao {
            get {
                return this.statusDescricaoField;
            }
            set {
                this.statusDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string SolicitanteId {
            get {
                return this.solicitanteIdField;
            }
            set {
                this.solicitanteIdField = value;
            }
        }
        
        /// <remarks/>
        public string SolicitanteCodigo {
            get {
                return this.solicitanteCodigoField;
            }
            set {
                this.solicitanteCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioCodigo {
            get {
                return this.usuarioCodigoField;
            }
            set {
                this.usuarioCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string SolicitanteNome {
            get {
                return this.solicitanteNomeField;
            }
            set {
                this.solicitanteNomeField = value;
            }
        }
        
        /// <remarks/>
        public string EmpresaCodigo {
            get {
                return this.empresaCodigoField;
            }
            set {
                this.empresaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string EmpresaCNPJ {
            get {
                return this.empresaCNPJField;
            }
            set {
                this.empresaCNPJField = value;
            }
        }
        
        /// <remarks/>
        public string EmpresaCodigoERP {
            get {
                return this.empresaCodigoERPField;
            }
            set {
                this.empresaCodigoERPField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaCodigo {
            get {
                return this.moedaCodigoField;
            }
            set {
                this.moedaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaDescricao {
            get {
                return this.moedaDescricaoField;
            }
            set {
                this.moedaDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorReembolso {
            get {
                return this.valorReembolsoField;
            }
            set {
                this.valorReembolsoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorAdiantamento {
            get {
                return this.valorAdiantamentoField;
            }
            set {
                this.valorAdiantamentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal CotacaoIndice {
            get {
                return this.cotacaoIndiceField;
            }
            set {
                this.cotacaoIndiceField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTotalIndice {
            get {
                return this.valorTotalIndiceField;
            }
            set {
                this.valorTotalIndiceField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorReembolsoIndice {
            get {
                return this.valorReembolsoIndiceField;
            }
            set {
                this.valorReembolsoIndiceField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorAdiantamentoIndice {
            get {
                return this.valorAdiantamentoIndiceField;
            }
            set {
                this.valorAdiantamentoIndiceField = value;
            }
        }
        
        /// <remarks/>
        public string TextoCabecalho {
            get {
                return this.textoCabecalhoField;
            }
            set {
                this.textoCabecalhoField = value;
            }
        }
        
        /// <remarks/>
        public string Chave {
            get {
                return this.chaveField;
            }
            set {
                this.chaveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class AdiantamentoLancamentoFinanceiro {
        
        private decimal valorTotalField;
        
        private string centroCustoCodigoField;
        
        private string centroCustoDescricaoField;
        
        private string unidadeNegocioField;
        
        private string projetoCodigoField;
        
        private string projetoDescricaoField;
        
        private string despesaCodigoField;
        
        private string despesaDescricaoField;
        
        /// <remarks/>
        public decimal ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoCodigo {
            get {
                return this.centroCustoCodigoField;
            }
            set {
                this.centroCustoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoDescricao {
            get {
                return this.centroCustoDescricaoField;
            }
            set {
                this.centroCustoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string UnidadeNegocio {
            get {
                return this.unidadeNegocioField;
            }
            set {
                this.unidadeNegocioField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoCodigo {
            get {
                return this.projetoCodigoField;
            }
            set {
                this.projetoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoDescricao {
            get {
                return this.projetoDescricaoField;
            }
            set {
                this.projetoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string DespesaCodigo {
            get {
                return this.despesaCodigoField;
            }
            set {
                this.despesaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string DespesaDescricao {
            get {
                return this.despesaDescricaoField;
            }
            set {
                this.despesaDescricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class AdiantamentoLancamentoContabil {
        
        private string contaCreditoField;
        
        private string contaDebitoField;
        
        private string centroCustoCodigoField;
        
        private string centroCustoDescricaoField;
        
        private string projetoCodigoField;
        
        private string projetoDescricaoField;
        
        private string unidadeNegocioField;
        
        private string historicoField;
        
        private decimal valorField;
        
        private decimal valorIndiceField;
        
        private string moedaCodigoField;
        
        private string moedaDescricaoField;
        
        private decimal cotacaoIndiceField;
        
        /// <remarks/>
        public string ContaCredito {
            get {
                return this.contaCreditoField;
            }
            set {
                this.contaCreditoField = value;
            }
        }
        
        /// <remarks/>
        public string ContaDebito {
            get {
                return this.contaDebitoField;
            }
            set {
                this.contaDebitoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoCodigo {
            get {
                return this.centroCustoCodigoField;
            }
            set {
                this.centroCustoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoDescricao {
            get {
                return this.centroCustoDescricaoField;
            }
            set {
                this.centroCustoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoCodigo {
            get {
                return this.projetoCodigoField;
            }
            set {
                this.projetoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoDescricao {
            get {
                return this.projetoDescricaoField;
            }
            set {
                this.projetoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string UnidadeNegocio {
            get {
                return this.unidadeNegocioField;
            }
            set {
                this.unidadeNegocioField = value;
            }
        }
        
        /// <remarks/>
        public string Historico {
            get {
                return this.historicoField;
            }
            set {
                this.historicoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorIndice {
            get {
                return this.valorIndiceField;
            }
            set {
                this.valorIndiceField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaCodigo {
            get {
                return this.moedaCodigoField;
            }
            set {
                this.moedaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaDescricao {
            get {
                return this.moedaDescricaoField;
            }
            set {
                this.moedaDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal CotacaoIndice {
            get {
                return this.cotacaoIndiceField;
            }
            set {
                this.cotacaoIndiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Adiantamento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class AdiantamentoResumido {
        
        private string codigoField;
        
        private string dataCriacaoField;
        
        private string dataEnvioField;
        
        private string dataNecssidadeField;
        
        private string dataPrevisaoPagamentoField;
        
        private string dataUltimaAprovacaoField;
        
        private string ultimoAprovadorCodigoField;
        
        private string ultimoAprovadorDescricaoField;
        
        private string statusCodigoField;
        
        private string statusDescricaoField;
        
        private string projetoCodigoField;
        
        private string projetoDescricaoField;
        
        private string centroCustoCodigoField;
        
        private string centroCustoDescricaoField;
        
        private string solicitanteCodigoField;
        
        private string usuarioCodigoField;
        
        private string solicitanteNomeField;
        
        private string moedaCodigoField;
        
        private string moedaDescricaoField;
        
        private decimal valorTotalField;
        
        private decimal valorAdiantamentoField;
        
        private string textoCabecalhoField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string DataCriacao {
            get {
                return this.dataCriacaoField;
            }
            set {
                this.dataCriacaoField = value;
            }
        }
        
        /// <remarks/>
        public string DataEnvio {
            get {
                return this.dataEnvioField;
            }
            set {
                this.dataEnvioField = value;
            }
        }
        
        /// <remarks/>
        public string DataNecssidade {
            get {
                return this.dataNecssidadeField;
            }
            set {
                this.dataNecssidadeField = value;
            }
        }
        
        /// <remarks/>
        public string DataPrevisaoPagamento {
            get {
                return this.dataPrevisaoPagamentoField;
            }
            set {
                this.dataPrevisaoPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string DataUltimaAprovacao {
            get {
                return this.dataUltimaAprovacaoField;
            }
            set {
                this.dataUltimaAprovacaoField = value;
            }
        }
        
        /// <remarks/>
        public string UltimoAprovadorCodigo {
            get {
                return this.ultimoAprovadorCodigoField;
            }
            set {
                this.ultimoAprovadorCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string UltimoAprovadorDescricao {
            get {
                return this.ultimoAprovadorDescricaoField;
            }
            set {
                this.ultimoAprovadorDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCodigo {
            get {
                return this.statusCodigoField;
            }
            set {
                this.statusCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescricao {
            get {
                return this.statusDescricaoField;
            }
            set {
                this.statusDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoCodigo {
            get {
                return this.projetoCodigoField;
            }
            set {
                this.projetoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoDescricao {
            get {
                return this.projetoDescricaoField;
            }
            set {
                this.projetoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoCodigo {
            get {
                return this.centroCustoCodigoField;
            }
            set {
                this.centroCustoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoDescricao {
            get {
                return this.centroCustoDescricaoField;
            }
            set {
                this.centroCustoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string SolicitanteCodigo {
            get {
                return this.solicitanteCodigoField;
            }
            set {
                this.solicitanteCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioCodigo {
            get {
                return this.usuarioCodigoField;
            }
            set {
                this.usuarioCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string SolicitanteNome {
            get {
                return this.solicitanteNomeField;
            }
            set {
                this.solicitanteNomeField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaCodigo {
            get {
                return this.moedaCodigoField;
            }
            set {
                this.moedaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaDescricao {
            get {
                return this.moedaDescricaoField;
            }
            set {
                this.moedaDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorAdiantamento {
            get {
                return this.valorAdiantamentoField;
            }
            set {
                this.valorAdiantamentoField = value;
            }
        }
        
        /// <remarks/>
        public string TextoCabecalho {
            get {
                return this.textoCabecalhoField;
            }
            set {
                this.textoCabecalhoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class Adiantamento : AdiantamentoResumido {
        
        private DadosColaborador usuarioDetalheField;
        
        private DadosColaborador solicitanteDetalheField;
        
        private DadosDocumentos solicitanteDocumentoField;
        
        private DadosBancarios solicitanteDadosBancariosField;
        
        private AdiantamentoLancamentoContabil[] lancamentosContabilidadeField;
        
        private AdiantamentoLancamentoFinanceiro[] lancamentosFinanceiroField;
        
        /// <remarks/>
        public DadosColaborador UsuarioDetalhe {
            get {
                return this.usuarioDetalheField;
            }
            set {
                this.usuarioDetalheField = value;
            }
        }
        
        /// <remarks/>
        public DadosColaborador SolicitanteDetalhe {
            get {
                return this.solicitanteDetalheField;
            }
            set {
                this.solicitanteDetalheField = value;
            }
        }
        
        /// <remarks/>
        public DadosDocumentos SolicitanteDocumento {
            get {
                return this.solicitanteDocumentoField;
            }
            set {
                this.solicitanteDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public DadosBancarios SolicitanteDadosBancarios {
            get {
                return this.solicitanteDadosBancariosField;
            }
            set {
                this.solicitanteDadosBancariosField = value;
            }
        }
        
        /// <remarks/>
        public AdiantamentoLancamentoContabil[] LancamentosContabilidade {
            get {
                return this.lancamentosContabilidadeField;
            }
            set {
                this.lancamentosContabilidadeField = value;
            }
        }
        
        /// <remarks/>
        public AdiantamentoLancamentoFinanceiro[] LancamentosFinanceiro {
            get {
                return this.lancamentosFinanceiroField;
            }
            set {
                this.lancamentosFinanceiroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class DadosColaborador {
        
        private string crachaField;
        
        private string usernameField;
        
        private string nomeField;
        
        private string centroCustoField;
        
        private string centroCustoDescricaoField;
        
        private string unidadeField;
        
        private string unidadeDescricaoField;
        
        private string superiorUsernameField;
        
        private string perfilAcessoField;
        
        private string perfilDespesaField;
        
        private string dataAlteracaoField;
        
        private string dataUltimoAcessoField;
        
        private string flagDesligadoField;
        
        private string flagAtivoField;
        
        private string fornecedorCodigoField;
        
        /// <remarks/>
        public string Cracha {
            get {
                return this.crachaField;
            }
            set {
                this.crachaField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCusto {
            get {
                return this.centroCustoField;
            }
            set {
                this.centroCustoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoDescricao {
            get {
                return this.centroCustoDescricaoField;
            }
            set {
                this.centroCustoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Unidade {
            get {
                return this.unidadeField;
            }
            set {
                this.unidadeField = value;
            }
        }
        
        /// <remarks/>
        public string UnidadeDescricao {
            get {
                return this.unidadeDescricaoField;
            }
            set {
                this.unidadeDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string SuperiorUsername {
            get {
                return this.superiorUsernameField;
            }
            set {
                this.superiorUsernameField = value;
            }
        }
        
        /// <remarks/>
        public string PerfilAcesso {
            get {
                return this.perfilAcessoField;
            }
            set {
                this.perfilAcessoField = value;
            }
        }
        
        /// <remarks/>
        public string PerfilDespesa {
            get {
                return this.perfilDespesaField;
            }
            set {
                this.perfilDespesaField = value;
            }
        }
        
        /// <remarks/>
        public string DataAlteracao {
            get {
                return this.dataAlteracaoField;
            }
            set {
                this.dataAlteracaoField = value;
            }
        }
        
        /// <remarks/>
        public string DataUltimoAcesso {
            get {
                return this.dataUltimoAcessoField;
            }
            set {
                this.dataUltimoAcessoField = value;
            }
        }
        
        /// <remarks/>
        public string FlagDesligado {
            get {
                return this.flagDesligadoField;
            }
            set {
                this.flagDesligadoField = value;
            }
        }
        
        /// <remarks/>
        public string FlagAtivo {
            get {
                return this.flagAtivoField;
            }
            set {
                this.flagAtivoField = value;
            }
        }
        
        /// <remarks/>
        public string FornecedorCodigo {
            get {
                return this.fornecedorCodigoField;
            }
            set {
                this.fornecedorCodigoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class DadosDocumentos {
        
        private string cPFField;
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class DadosBancarios {
        
        private string bancoField;
        
        private string agenciaField;
        
        private string contaField;
        
        private string contaDigitoField;
        
        /// <remarks/>
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Conta {
            get {
                return this.contaField;
            }
            set {
                this.contaField = value;
            }
        }
        
        /// <remarks/>
        public string ContaDigito {
            get {
                return this.contaDigitoField;
            }
            set {
                this.contaDigitoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class RelatorioDespesaLancamentoFinanceiro {
        
        private string valorTotalField;
        
        private string centroCustoCodigoField;
        
        private string centroCustoDescricaoField;
        
        private string unidadeNegocioField;
        
        private string projetoCodigoField;
        
        private string projetoDescricaoField;
        
        private string despesaCodigoField;
        
        private string despesaDescricaoField;
        
        /// <remarks/>
        public string ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoCodigo {
            get {
                return this.centroCustoCodigoField;
            }
            set {
                this.centroCustoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoDescricao {
            get {
                return this.centroCustoDescricaoField;
            }
            set {
                this.centroCustoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string UnidadeNegocio {
            get {
                return this.unidadeNegocioField;
            }
            set {
                this.unidadeNegocioField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoCodigo {
            get {
                return this.projetoCodigoField;
            }
            set {
                this.projetoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoDescricao {
            get {
                return this.projetoDescricaoField;
            }
            set {
                this.projetoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string DespesaCodigo {
            get {
                return this.despesaCodigoField;
            }
            set {
                this.despesaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string DespesaDescricao {
            get {
                return this.despesaDescricaoField;
            }
            set {
                this.despesaDescricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class RelatorioDespesaLancamentoContabil {
        
        private string codigoField;
        
        private string lancamentoField;
        
        private string contaCreditoField;
        
        private string contaDebitoField;
        
        private string codigoIntegracaoField;
        
        private string centroCustoCodigoField;
        
        private string centroCustoDescricaoField;
        
        private string projetoCodigoField;
        
        private string projetoDescricaoField;
        
        private string unidadeNegocioField;
        
        private string historicoField;
        
        private decimal valorField;
        
        private decimal valorIndiceField;
        
        private string moedaCodigoField;
        
        private string moedaDescricaoField;
        
        private decimal cotacaoIndiceField;
        
        private string rateio01Field;
        
        private string rateio02Field;
        
        private string rateio03Field;
        
        private string rateio04Field;
        
        private string rateio05Field;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Lancamento {
            get {
                return this.lancamentoField;
            }
            set {
                this.lancamentoField = value;
            }
        }
        
        /// <remarks/>
        public string ContaCredito {
            get {
                return this.contaCreditoField;
            }
            set {
                this.contaCreditoField = value;
            }
        }
        
        /// <remarks/>
        public string ContaDebito {
            get {
                return this.contaDebitoField;
            }
            set {
                this.contaDebitoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoIntegracao {
            get {
                return this.codigoIntegracaoField;
            }
            set {
                this.codigoIntegracaoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoCodigo {
            get {
                return this.centroCustoCodigoField;
            }
            set {
                this.centroCustoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string CentroCustoDescricao {
            get {
                return this.centroCustoDescricaoField;
            }
            set {
                this.centroCustoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoCodigo {
            get {
                return this.projetoCodigoField;
            }
            set {
                this.projetoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoDescricao {
            get {
                return this.projetoDescricaoField;
            }
            set {
                this.projetoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string UnidadeNegocio {
            get {
                return this.unidadeNegocioField;
            }
            set {
                this.unidadeNegocioField = value;
            }
        }
        
        /// <remarks/>
        public string Historico {
            get {
                return this.historicoField;
            }
            set {
                this.historicoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorIndice {
            get {
                return this.valorIndiceField;
            }
            set {
                this.valorIndiceField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaCodigo {
            get {
                return this.moedaCodigoField;
            }
            set {
                this.moedaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaDescricao {
            get {
                return this.moedaDescricaoField;
            }
            set {
                this.moedaDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal CotacaoIndice {
            get {
                return this.cotacaoIndiceField;
            }
            set {
                this.cotacaoIndiceField = value;
            }
        }
        
        /// <remarks/>
        public string Rateio01 {
            get {
                return this.rateio01Field;
            }
            set {
                this.rateio01Field = value;
            }
        }
        
        /// <remarks/>
        public string Rateio02 {
            get {
                return this.rateio02Field;
            }
            set {
                this.rateio02Field = value;
            }
        }
        
        /// <remarks/>
        public string Rateio03 {
            get {
                return this.rateio03Field;
            }
            set {
                this.rateio03Field = value;
            }
        }
        
        /// <remarks/>
        public string Rateio04 {
            get {
                return this.rateio04Field;
            }
            set {
                this.rateio04Field = value;
            }
        }
        
        /// <remarks/>
        public string Rateio05 {
            get {
                return this.rateio05Field;
            }
            set {
                this.rateio05Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class RelatorioDespesaLancamentoAnexo {
        
        private string urlAnexoField;
        
        /// <remarks/>
        public string UrlAnexo {
            get {
                return this.urlAnexoField;
            }
            set {
                this.urlAnexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class RelatorioDespesaLancamento {
        
        private string codigoField;
        
        private string moedaCodigoField;
        
        private string tipoDespesaField;
        
        private string moedaDescricaoField;
        
        private decimal cotacaoIndiceField;
        
        private decimal valorTotalField;
        
        private decimal valorReembolsoField;
        
        private decimal valorTotalIndiceField;
        
        private decimal valorReembolsoIndiceField;
        
        private string flagDevolucaoField;
        
        private string tipoDespesaCodigoField;
        
        private string tipoDespesaDescricaoField;
        
        private string projetoCodigoField;
        
        private string projetoDescricaoField;
        
        private string comentariosField;
        
        private string descricaoAutomaticaField;
        
        private decimal quantidadeKMField;
        
        private int quantidadePessoasField;
        
        private int quantidadeDiasHospedagemField;
        
        private string cursoDescricaoField;
        
        private string textoItemField;
        
        private string dataPrevisaoPagamentoField;
        
        private string lancamentoField;
        
        private string chaveField;
        
        private RelatorioDespesaLancamentoAnexo[] anexosField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaCodigo {
            get {
                return this.moedaCodigoField;
            }
            set {
                this.moedaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDespesa {
            get {
                return this.tipoDespesaField;
            }
            set {
                this.tipoDespesaField = value;
            }
        }
        
        /// <remarks/>
        public string MoedaDescricao {
            get {
                return this.moedaDescricaoField;
            }
            set {
                this.moedaDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal CotacaoIndice {
            get {
                return this.cotacaoIndiceField;
            }
            set {
                this.cotacaoIndiceField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorReembolso {
            get {
                return this.valorReembolsoField;
            }
            set {
                this.valorReembolsoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTotalIndice {
            get {
                return this.valorTotalIndiceField;
            }
            set {
                this.valorTotalIndiceField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorReembolsoIndice {
            get {
                return this.valorReembolsoIndiceField;
            }
            set {
                this.valorReembolsoIndiceField = value;
            }
        }
        
        /// <remarks/>
        public string FlagDevolucao {
            get {
                return this.flagDevolucaoField;
            }
            set {
                this.flagDevolucaoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDespesaCodigo {
            get {
                return this.tipoDespesaCodigoField;
            }
            set {
                this.tipoDespesaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDespesaDescricao {
            get {
                return this.tipoDespesaDescricaoField;
            }
            set {
                this.tipoDespesaDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoCodigo {
            get {
                return this.projetoCodigoField;
            }
            set {
                this.projetoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string ProjetoDescricao {
            get {
                return this.projetoDescricaoField;
            }
            set {
                this.projetoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoAutomatica {
            get {
                return this.descricaoAutomaticaField;
            }
            set {
                this.descricaoAutomaticaField = value;
            }
        }
        
        /// <remarks/>
        public decimal QuantidadeKM {
            get {
                return this.quantidadeKMField;
            }
            set {
                this.quantidadeKMField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadePessoas {
            get {
                return this.quantidadePessoasField;
            }
            set {
                this.quantidadePessoasField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeDiasHospedagem {
            get {
                return this.quantidadeDiasHospedagemField;
            }
            set {
                this.quantidadeDiasHospedagemField = value;
            }
        }
        
        /// <remarks/>
        public string CursoDescricao {
            get {
                return this.cursoDescricaoField;
            }
            set {
                this.cursoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string TextoItem {
            get {
                return this.textoItemField;
            }
            set {
                this.textoItemField = value;
            }
        }
        
        /// <remarks/>
        public string DataPrevisaoPagamento {
            get {
                return this.dataPrevisaoPagamentoField;
            }
            set {
                this.dataPrevisaoPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string Lancamento {
            get {
                return this.lancamentoField;
            }
            set {
                this.lancamentoField = value;
            }
        }
        
        /// <remarks/>
        public string Chave {
            get {
                return this.chaveField;
            }
            set {
                this.chaveField = value;
            }
        }
        
        /// <remarks/>
        public RelatorioDespesaLancamentoAnexo[] Anexos {
            get {
                return this.anexosField;
            }
            set {
                this.anexosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aptuscloud.com.br/rdapi/")]
    public partial class RelatorioDespesa : RelatorioDespesaResumido {
        
        private DadosColaborador usuarioDetalheField;
        
        private DadosColaborador solicitanteDetalheField;
        
        private DadosDocumentos solicitanteDocumentoField;
        
        private DadosBancarios solicitanteDadosBancariosField;
        
        private RelatorioDespesaLancamento[] lancamentosField;
        
        private RelatorioDespesaLancamentoContabil[] lancamentosContabilidadeField;
        
        private RelatorioDespesaLancamentoFinanceiro[] lancamentosFinanceiroField;
        
        /// <remarks/>
        public DadosColaborador UsuarioDetalhe {
            get {
                return this.usuarioDetalheField;
            }
            set {
                this.usuarioDetalheField = value;
            }
        }
        
        /// <remarks/>
        public DadosColaborador SolicitanteDetalhe {
            get {
                return this.solicitanteDetalheField;
            }
            set {
                this.solicitanteDetalheField = value;
            }
        }
        
        /// <remarks/>
        public DadosDocumentos SolicitanteDocumento {
            get {
                return this.solicitanteDocumentoField;
            }
            set {
                this.solicitanteDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public DadosBancarios SolicitanteDadosBancarios {
            get {
                return this.solicitanteDadosBancariosField;
            }
            set {
                this.solicitanteDadosBancariosField = value;
            }
        }
        
        /// <remarks/>
        public RelatorioDespesaLancamento[] Lancamentos {
            get {
                return this.lancamentosField;
            }
            set {
                this.lancamentosField = value;
            }
        }
        
        /// <remarks/>
        public RelatorioDespesaLancamentoContabil[] LancamentosContabilidade {
            get {
                return this.lancamentosContabilidadeField;
            }
            set {
                this.lancamentosContabilidadeField = value;
            }
        }
        
        /// <remarks/>
        public RelatorioDespesaLancamentoFinanceiro[] LancamentosFinanceiro {
            get {
                return this.lancamentosFinanceiroField;
            }
            set {
                this.lancamentosFinanceiroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AtualizarIntegradoSituacaoCompletedEventHandler(object sender, AtualizarIntegradoSituacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarIntegradoSituacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarIntegradoSituacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoEletronica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoEletronica)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AtualizarIntegracaoSucessoCompletedEventHandler(object sender, AtualizarIntegracaoSucessoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarIntegracaoSucessoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarIntegracaoSucessoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoEletronica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoEletronica)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AtualizarIntegracaoProblemaCompletedEventHandler(object sender, AtualizarIntegracaoProblemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarIntegracaoProblemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarIntegracaoProblemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoEletronica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoEletronica)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void EstornarIntegracaoCompletedEventHandler(object sender, EstornarIntegracaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstornarIntegracaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstornarIntegracaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoEletronica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoEletronica)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ObterAdiantamentoCompletedEventHandler(object sender, ObterAdiantamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterAdiantamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterAdiantamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoEletronica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoEletronica)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ObterAdiantamentosPendentesResumoCompletedEventHandler(object sender, ObterAdiantamentosPendentesResumoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterAdiantamentosPendentesResumoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterAdiantamentosPendentesResumoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoEletronica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoEletronica)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ObterAdiantamentosPendentesCompletedEventHandler(object sender, ObterAdiantamentosPendentesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterAdiantamentosPendentesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterAdiantamentosPendentesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoEletronica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoEletronica)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591